"""BOUND adoption catalog derived from reusable patterns in FreeLLMAPI and Awesome LLM Apps.

The catalog is deliberately conservative about exclusion. Anything plausibly useful to an
IT operations assistant stays visible as adopted, candidate, or hold. Only clearly
out-of-scope consumer/medical/game patterns are excluded.
"""

BOUND_CAPABILITY_CATALOG = [
    {
        "id": "inference_gateway",
        "name": "Unified inference gateway",
        "source": "FreeLLMAPI",
        "status": "adopted",
        "area": "inference",
        "summary": "OpenAI-compatible local gateway with provider fallback, quota awareness and model routing.",
    },
    {
        "id": "provider_health",
        "name": "Provider health and fallback telemetry",
        "source": "FreeLLMAPI",
        "status": "adopted",
        "area": "inference",
        "summary": "Record routed model, fallback trail, latency and availability without coupling agents to providers.",
    },
    {
        "id": "fusion_reasoning",
        "name": "Multi-model synthesis",
        "source": "FreeLLMAPI + Awesome LLM Apps",
        "status": "candidate",
        "area": "reasoning",
        "summary": "Use a panel/judge pattern selectively for high-value reasoning, not for every turn.",
    },
    {
        "id": "trust_gated_agents",
        "name": "Trust-gated agents",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "security",
        "summary": "New agents, skills and MCP packages enter quarantine and must pass security gates before enablement.",
    },
    {
        "id": "skillspector_gate",
        "name": "SkillSpector intake gate",
        "source": "NVIDIA SkillSpector",
        "status": "adopted",
        "area": "security",
        "summary": "Static security scan is mandatory for every imported skill/agent/MCP package before approval.",
    },
    {
        "id": "eval_gated_improvement",
        "name": "Evaluation-gated improvement",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "agents",
        "summary": "Propose one bounded agent change, evaluate baseline versus candidate, then require human promotion.",
    },
    {
        "id": "multi_mcp_router",
        "name": "Per-agent capability isolation",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "tools",
        "summary": "Specialists receive only the tools and MCP servers required for their mandate.",
    },
    {
        "id": "always_on_agents",
        "name": "Always-on/event agents",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "automation",
        "summary": "Scheduled and event-driven work defaults to dry-run and internal artifacts before external delivery.",
    },
    {
        "id": "shared_memory",
        "name": "Shared cross-model memory",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "memory",
        "summary": "Keep durable environment and agent knowledge independent from the serving model.",
    },
    {
        "id": "corrective_rag",
        "name": "Corrective and typed RAG",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Grade retrieval quality, retry weak evidence, and cite exact sources instead of treating retrieval as truth.",
    },
    {
        "id": "knowledge_graph_rag",
        "name": "Knowledge graph RAG",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Represent infrastructure relationships explicitly for multi-hop operational questions.",
    },
    {
        "id": "generative_ui",
        "name": "Structured generative workspace",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "ui",
        "summary": "Agents return structured operational state that renders as evidence, actions, risks and approvals rather than prose alone.",
    },
    {
        "id": "browser_automation",
        "name": "Browser automation",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "tools",
        "summary": "Potentially useful for admin portals, but must sit behind explicit operator control, scoped sessions and audit.",
    },
    {
        "id": "voice_operator",
        "name": "Voice operator surface",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "ui",
        "summary": "Potential future hands-free interface; no need to bind operational authority to voice in the first releases.",
    },
    {
        "id": "data_analysis",
        "name": "File and tabular analysis",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "analysis",
        "summary": "Useful for logs, exports, inventories, billing and network data with provenance retained.",
    },
    {
        "id": "deep_research",
        "name": "Evidence-backed research agent",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "research",
        "summary": "Useful for vendors, products, standards and incident background when sources and freshness are explicit.",
    },
    {
        "id": "meeting_brief",
        "name": "Meeting brief agent",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "business",
        "summary": "Prepare concise stakeholder context, decisions and open questions from trusted internal sources.",
    },
    {
        "id": "autonomous_payments",
        "name": "Autonomous payment agent",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "finance",
        "summary": "Potentially relevant to procurement later, but autonomous spend is prohibited without a dedicated approval boundary.",
    },
    {
        "id": "scope_creep_detector",
        "name": "Scope creep detector",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "engineering",
        "summary": "Compare a change against its stated intent and flag unplanned authority, dependency or feature expansion.",
    },
    {
        "id": "commit_archaeology",
        "name": "Commit archaeology",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "engineering",
        "summary": "Reconstruct why operational code or configuration exists before BOUND recommends changing it.",
    },
    {
        "id": "dependency_doctor",
        "name": "Dependency doctor",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "engineering",
        "summary": "Inspect dependency manifests for obsolete, risky, duplicate or poorly constrained packages before deployment.",
    },
    {
        "id": "change_impact_ripple",
        "name": "Change impact / Ripple",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "operations",
        "summary": "When one setting changes, identify related documentation, configuration and dependent systems that may need review.",
    },
    {
        "id": "system_architect",
        "name": "System architecture review",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "engineering",
        "summary": "Structured architecture critique for BOUND, client systems and infrastructure projects.",
    },
    {
        "id": "consultant_agent",
        "name": "Consulting research agent",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "business",
        "summary": "Research and strategy workflow useful to BOUND's consulting role when sources remain explicit.",
    },
    {
        "id": "vendor_intelligence",
        "name": "Vendor and product intelligence",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "procurement",
        "summary": "Gather product, release and supplier signals for procurement and technology planning.",
    },
    {
        "id": "release_radar",
        "name": "Release radar",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "automation",
        "summary": "Watch dependencies and platform releases for breaking, deprecated and security-relevant changes.",
    },
    {
        "id": "github_mcp",
        "name": "GitHub MCP specialist access",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "tools",
        "summary": "Repository-aware specialists with scoped read/write permissions rather than global GitHub access.",
    },
    {
        "id": "remote_mcp_bridge",
        "name": "Remote MCP bridge",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "tools",
        "summary": "Potential route to remote operational tools after authentication, provenance and trust boundaries are mature.",
    },
    {
        "id": "chat_with_operational_sources",
        "name": "Chat with operational sources",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Unified retrieval over PDFs, repositories, mail and other approved sources with source-specific permissions.",
    },
    {
        "id": "multimodal_rag",
        "name": "Multimodal RAG",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Use diagrams, screenshots, PDF pages, audio and video as cited evidence when text extraction is insufficient.",
    },
    {
        "id": "rag_diagnostics",
        "name": "RAG failure diagnostics",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Diagnose bad retrieval, weak grounding and stale evidence rather than trusting a retrieval pipeline blindly.",
    },
    {
        "id": "token_optimisation",
        "name": "Context and token optimisation",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "inference",
        "summary": "Reduce repeated context and tool-output overhead while preserving evidence and operational meaning.",
    },
    {
        "id": "agent_prompt_autoresearch",
        "name": "Eval-gated prompt autoresearch",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "agents",
        "summary": "Allow bounded prompt experiments only in isolated evaluation branches; never self-promote changes.",
    },
    {
        "id": "teaching_support",
        "name": "Teaching and training support",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "school",
        "summary": "Could support staff/student technical learning, but is secondary to BOUND's operational mandate.",
    },
    {
        "id": "recruitment_support",
        "name": "Recruitment workflow support",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "business",
        "summary": "Potential business/admin workflow, retained without granting autonomous hiring authority.",
    },
    {
        "id": "finance_analysis_team",
        "name": "Finance analysis team",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "finance",
        "summary": "Useful for budgets, quotes and comparisons, but financial actions remain advisory and approval-gated.",
    },
    {
        "id": "tamper_evident_audit",
        "name": "Tamper-evident audit chain",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "security",
        "summary": "Hash-chain security and execution events once the audit writer is made atomic under concurrent workers.",
    },
    {
        "id": "medical_diagnosis",
        "name": "Medical diagnostic agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "Outside BOUND's operational IT mandate.",
    },
    {
        "id": "mental_wellbeing",
        "name": "Mental wellbeing agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "Outside BOUND's operational IT mandate.",
    },
    {
        "id": "autonomous_games",
        "name": "Autonomous game-playing agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "No operational value for BOUND.",
    },
]
