"""BOUND adoption catalog derived from reusable patterns in FreeLLMAPI and Awesome LLM Apps.

The catalog is deliberately conservative about exclusion. Anything plausibly useful to an
IT operations assistant stays visible as adopted, candidate, or hold. Only clearly
out-of-scope consumer/medical/game patterns are excluded.
"""

BOUND_CAPABILITY_CATALOG = [
    {
        "id": "inference_gateway",
        "name": "Unified inference gateway",
        "source": "FreeLLMAPI",
        "status": "adopted",
        "area": "inference",
        "summary": "OpenAI-compatible local gateway with provider fallback, quota awareness and model routing.",
    },
    {
        "id": "provider_health",
        "name": "Provider health and fallback telemetry",
        "source": "FreeLLMAPI",
        "status": "adopted",
        "area": "inference",
        "summary": "Record routed model, fallback trail, latency and availability without coupling agents to providers.",
    },
    {
        "id": "fusion_reasoning",
        "name": "Multi-model synthesis",
        "source": "FreeLLMAPI + Awesome LLM Apps",
        "status": "candidate",
        "area": "reasoning",
        "summary": "Use a panel/judge pattern selectively for high-value reasoning, not for every turn.",
    },
    {
        "id": "trust_gated_agents",
        "name": "Trust-gated agents",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "security",
        "summary": "New agents, skills and MCP packages enter quarantine and must pass security gates before enablement.",
    },
    {
        "id": "skillspector_gate",
        "name": "SkillSpector intake gate",
        "source": "NVIDIA SkillSpector",
        "status": "adopted",
        "area": "security",
        "summary": "Static security scan is mandatory for every imported skill/agent/MCP package before approval.",
    },
    {
        "id": "eval_gated_improvement",
        "name": "Evaluation-gated improvement",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "agents",
        "summary": "Propose one bounded agent change, evaluate baseline versus candidate, then require human promotion.",
    },
    {
        "id": "multi_mcp_router",
        "name": "Per-agent capability isolation",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "tools",
        "summary": "Specialists receive only the tools and MCP servers required for their mandate.",
    },
    {
        "id": "always_on_agents",
        "name": "Always-on/event agents",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "automation",
        "summary": "Scheduled and event-driven work defaults to dry-run and internal artifacts before external delivery.",
    },
    {
        "id": "shared_memory",
        "name": "Shared cross-model memory",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "memory",
        "summary": "Keep durable environment and agent knowledge independent from the serving model.",
    },
    {
        "id": "corrective_rag",
        "name": "Corrective and typed RAG",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Grade retrieval quality, retry weak evidence, and cite exact sources instead of treating retrieval as truth.",
    },
    {
        "id": "knowledge_graph_rag",
        "name": "Knowledge graph RAG",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "knowledge",
        "summary": "Represent infrastructure relationships explicitly for multi-hop operational questions.",
    },
    {
        "id": "generative_ui",
        "name": "Structured generative workspace",
        "source": "Awesome LLM Apps",
        "status": "adopted",
        "area": "ui",
        "summary": "Agents return structured operational state that renders as evidence, actions, risks and approvals rather than prose alone.",
    },
    {
        "id": "browser_automation",
        "name": "Browser automation",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "tools",
        "summary": "Potentially useful for admin portals, but must sit behind explicit operator control, scoped sessions and audit.",
    },
    {
        "id": "voice_operator",
        "name": "Voice operator surface",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "ui",
        "summary": "Potential future hands-free interface; no need to bind operational authority to voice in the first releases.",
    },
    {
        "id": "data_analysis",
        "name": "File and tabular analysis",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "analysis",
        "summary": "Useful for logs, exports, inventories, billing and network data with provenance retained.",
    },
    {
        "id": "deep_research",
        "name": "Evidence-backed research agent",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "research",
        "summary": "Useful for vendors, products, standards and incident background when sources and freshness are explicit.",
    },
    {
        "id": "meeting_brief",
        "name": "Meeting brief agent",
        "source": "Awesome LLM Apps",
        "status": "candidate",
        "area": "business",
        "summary": "Prepare concise stakeholder context, decisions and open questions from trusted internal sources.",
    },
    {
        "id": "autonomous_payments",
        "name": "Autonomous payment agent",
        "source": "Awesome LLM Apps",
        "status": "hold",
        "area": "finance",
        "summary": "Potentially relevant to procurement later, but autonomous spend is prohibited without a dedicated approval boundary.",
    },
    {
        "id": "medical_diagnosis",
        "name": "Medical diagnostic agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "Outside BOUND's operational IT mandate.",
    },
    {
        "id": "mental_wellbeing",
        "name": "Mental wellbeing agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "Outside BOUND's operational IT mandate.",
    },
    {
        "id": "autonomous_games",
        "name": "Autonomous game-playing agents",
        "source": "Awesome LLM Apps",
        "status": "excluded",
        "area": "consumer",
        "summary": "No operational value for BOUND.",
    },
]
